# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
game_versions_mr=26.2
game_versions_curse=26.2
# parchment_version=1.21.11:2025.12.20 - after 1.21.11 mappings not request
loader_version=0.19.3

# Mod Properties
mod_version=2.7.5.2
maven_group=red.jackf
archives_base_name=whereisit

# Dependencies
jackfredlib_version=0.10.6+26.2
yacl_version=3.9.4+26.2-fabric

jei_modrinth_id=1rsoIkuL

# JF_AUTO_UPDATE_BLOCK
fabric-api_version=0.153.0+26.2
modmenu_version=20.0.0-beta.2
jei_version=30.0.0.4
rei_version=26.2.820
# emi_version=1.1.16+1.21.1 - no support for new version
# JF_END_AUTO_UPDATE_BLOCK

# Publishing
prefix=[26.2]
release_type=release
changelog_filter=[feat],[fix],[change],[docs],[update]
mod_name=Where Is It (Unofficial Port)
github_owner=ponuing
github_repo=WhereIsIt
github_url=https://github.com/ponuing/WhereIsIt

# Publishing Testing
#lastTag=v2.0.16
#newTag=v2.0.17
